spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          destination: R2
          content-type: application/*+avro
          producer:
            useNativeEncoding: true # Enables using the custom serializer
        consumer-in-0:
          destination: R2
          content-type: application/*+avro
          consumer:
            use-native-decoding: true # Enables using the custom deserializer
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.metamorphosis.kafkajsonsolution.serializers.AvroSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.metamorphosis.kafkajsonsolution.serializers.AvroDeserializer
